// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SessyData.Model;

#nullable disable

namespace SessyData.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20260515134448_FixSolarProductionKwh")]
    partial class FixSolarProductionKwh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("SessyData.Model.Consumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ConsumptionWh")
                        .HasColumnType("REAL");

                    b.Property<double>("GlobalRadiation")
                        .HasColumnType("REAL");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Time");

                    b.ToTable("Consumption");
                });

            modelBuilder.Entity("SessyData.Model.EPEXPrices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Time");

                    b.ToTable("EPEXPrices");
                });

            modelBuilder.Entity("SessyData.Model.EnergyHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ConsumedTariff1")
                        .HasColumnType("REAL");

                    b.Property<double>("ConsumedTariff2")
                        .HasColumnType("REAL");

                    b.Property<double>("GlobalRadiation")
                        .HasColumnType("REAL");

                    b.Property<string>("MeterId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ProducedTariff1")
                        .HasColumnType("REAL");

                    b.Property<double>("ProducedTariff2")
                        .HasColumnType("REAL");

                    b.Property<int>("TarrifIndicator")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Time");

                    b.ToTable("EnergyHistory");
                });

            modelBuilder.Entity("SessyData.Model.InverterMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InverterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SolarProductionKWh")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InverterId");

                    b.HasIndex("Time");

                    b.ToTable("InverterMeasurements");
                });

            modelBuilder.Entity("SessyData.Model.Investment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmountEur")
                        .HasColumnType("REAL");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedAnnualSavingsEur")
                        .HasColumnType("REAL");

                    b.Property<int>("ExpectedLifetimeYears")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SavingsDescription")
                        .HasColumnType("TEXT");

                    b.Property<double>("SubsidyEur")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseDate");

                    b.ToTable("Investment");
                });

            modelBuilder.Entity("SessyData.Model.QuarterlyMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatteryMode")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BatteryPowerWatts")
                        .HasColumnType("REAL");

                    b.Property<double>("BatteryStateOfChargeWh")
                        .HasColumnType("REAL");

                    b.Property<double>("BuyingPriceEur")
                        .HasColumnType("REAL");

                    b.Property<double>("GlobalRadiation")
                        .HasColumnType("REAL");

                    b.Property<double>("GridExportWh")
                        .HasColumnType("REAL");

                    b.Property<double>("GridImportWh")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsReliable")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SellingPriceEur")
                        .HasColumnType("REAL");

                    b.Property<double>("SolarProductionKWh")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Time");

                    b.ToTable("QuarterlyMeasurements");
                });

            modelBuilder.Entity("SessyData.Model.SessyStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusDetails")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Time");

                    b.ToTable("SessyStatusHistory");
                });

            modelBuilder.Entity("SessyData.Model.SessyWebControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Time");

                    b.ToTable("SessyWebControl");
                });

            modelBuilder.Entity("SessyData.Model.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CycleCost")
                        .HasColumnType("REAL");

                    b.Property<string>("DatabaseBackupDirectory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManualOverride")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NetZeroHomeMinProfit")
                        .HasColumnType("REAL");

                    b.Property<string>("RequiredHomeEnergy")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SolarCorrection")
                        .HasColumnType("REAL");

                    b.Property<bool>("SolarSystemShutsDownDuringNegativePrices")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("SessyData.Model.SolarData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("GlobalRadiation")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Time");

                    b.ToTable("SolarData");
                });

            modelBuilder.Entity("SessyData.Model.SolarInverterData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InverterId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Power")
                        .HasColumnType("REAL");

                    b.Property<string>("ProviderName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Time");

                    b.ToTable("SolarInverterData");
                });

            modelBuilder.Entity("SessyData.Model.Taxes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CapacityTransportFee")
                        .HasColumnType("REAL");

                    b.Property<double>("EnergyTax")
                        .HasColumnType("REAL");

                    b.Property<double>("FixedTransportFee")
                        .HasColumnType("REAL");

                    b.Property<double>("NetManagementCost")
                        .HasColumnType("REAL");

                    b.Property<bool>("Netting")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PurchaseCompensation")
                        .HasColumnType("REAL");

                    b.Property<double>("ReturnDeliveryCompensation")
                        .HasColumnType("REAL");

                    b.Property<double>("TaxReduction")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("TEXT");

                    b.Property<double>("ValueAddedTax")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Taxes");
                });
#pragma warning restore 612, 618
        }
    }
}
